# Generated by Django 3.0.2 on 2020-01-15 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LuggageType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('FULL', 'FULL'), ('AVAILABALE', 'AVAILABALE')], default='AVAILABALE', max_length=128)),
            ],
            options={
                'verbose_name': 'LuggageType',
                'verbose_name_plural': 'Luggage Types',
                'db_table': 'Luggage',
            },
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('IS_BOOK', 'BOOK STATUS'), ('IS_POST', 'POST STATUS')], default='IS_BOOK', max_length=128)),
                ('maximum_booking', models.IntegerField(default=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'usertab',
                'verbose_name_plural': 'users info',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_price', models.IntegerField(blank=True, null=True)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booked_booking_objects', to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(blank=True, related_name='items', to='api.LuggageType')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'Book',
            },
        ),
    ]
